name: Continuous Integration
on:
    push:
        branches:
            -main
            -jenk
    workflow_dispatch:
jobs:
    my_first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Set up JDK 17
              uses: action/setup-java@v3
              with:
                java-version: '17'
                distribution: 'zulu'
            - name: Show Java version
              run: "java -version"
            
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                ref: jenk

            - name: Show directory
              run: 'pwd'
              
            - name: List files
              run: 'is -la'
              
            - name: Install Dependencies
              run: 'mnv compile'
              
            - name: Build application
              run: 'mnv package -DskipTests'

            - name: Test application
              run: 'mnv test'  

